DB_NAME = 'HERE_YOUR_DB_NAME'
DB_USER = 'HERE_YOUR_DB_USER'
DB_PASSWORD = 'HERE_YOUR_DB_PASSWORD'
DB_ADDRESS = 'HERE_YOUR_DB_ADDRESS'
debug = False
ERROR_INCLUDE_MESSAGE = False
SEND_FILE_MAX_AGE_DEFAULT = 30
SQLALCHEMY_TRACK_MODIFICATIONS = False
